// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ServerReady {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ServerReady {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsServerReady(bb:flatbuffers.ByteBuffer, obj?:ServerReady):ServerReady {
  return (obj || new ServerReady()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsServerReady(bb:flatbuffers.ByteBuffer, obj?:ServerReady):ServerReady {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ServerReady()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

heartbeatIntervalMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startServerReady(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addHeartbeatIntervalMs(builder:flatbuffers.Builder, heartbeatIntervalMs:bigint) {
  builder.addFieldInt64(0, heartbeatIntervalMs, BigInt('0'));
}

static endServerReady(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createServerReady(builder:flatbuffers.Builder, heartbeatIntervalMs:bigint):flatbuffers.Offset {
  ServerReady.startServerReady(builder);
  ServerReady.addHeartbeatIntervalMs(builder, heartbeatIntervalMs);
  return ServerReady.endServerReady(builder);
}
}
