// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GroupRemoved {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): GroupRemoved {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsGroupRemoved(bb: flatbuffers.ByteBuffer, obj?: GroupRemoved): GroupRemoved {
    return (obj || new GroupRemoved()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsGroupRemoved(
    bb: flatbuffers.ByteBuffer,
    obj?: GroupRemoved
  ): GroupRemoved {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new GroupRemoved()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  groupId(): string | null;
  groupId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  groupId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  static startGroupRemoved(builder: flatbuffers.Builder) {
    builder.startObject(1);
  }

  static addGroupId(builder: flatbuffers.Builder, groupIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, groupIdOffset, 0);
  }

  static endGroupRemoved(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createGroupRemoved(
    builder: flatbuffers.Builder,
    groupIdOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    GroupRemoved.startGroupRemoved(builder);
    GroupRemoved.addGroupId(builder, groupIdOffset);
    return GroupRemoved.endGroupRemoved(builder);
  }
}
