// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GroupParticipantAdded {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): GroupParticipantAdded {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsGroupParticipantAdded(
    bb: flatbuffers.ByteBuffer,
    obj?: GroupParticipantAdded
  ): GroupParticipantAdded {
    return (obj || new GroupParticipantAdded()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsGroupParticipantAdded(
    bb: flatbuffers.ByteBuffer,
    obj?: GroupParticipantAdded
  ): GroupParticipantAdded {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new GroupParticipantAdded()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  groupId(): string | null;
  groupId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  groupId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  participantId(): string | null;
  participantId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  participantId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  static startGroupParticipantAdded(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addGroupId(builder: flatbuffers.Builder, groupIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, groupIdOffset, 0);
  }

  static addParticipantId(builder: flatbuffers.Builder, participantIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, participantIdOffset, 0);
  }

  static endGroupParticipantAdded(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createGroupParticipantAdded(
    builder: flatbuffers.Builder,
    groupIdOffset: flatbuffers.Offset,
    participantIdOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    GroupParticipantAdded.startGroupParticipantAdded(builder);
    GroupParticipantAdded.addGroupId(builder, groupIdOffset);
    GroupParticipantAdded.addParticipantId(builder, participantIdOffset);
    return GroupParticipantAdded.endGroupParticipantAdded(builder);
  }
}
