// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class GroupSessionRequest {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): GroupSessionRequest {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsGroupSessionRequest(
    bb: flatbuffers.ByteBuffer,
    obj?: GroupSessionRequest
  ): GroupSessionRequest {
    return (obj || new GroupSessionRequest()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsGroupSessionRequest(
    bb: flatbuffers.ByteBuffer,
    obj?: GroupSessionRequest
  ): GroupSessionRequest {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new GroupSessionRequest()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  groupId(): string | null;
  groupId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  groupId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  sessionId(): string | null;
  sessionId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  sessionId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  static startGroupSessionRequest(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addGroupId(builder: flatbuffers.Builder, groupIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, groupIdOffset, 0);
  }

  static addSessionId(builder: flatbuffers.Builder, sessionIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, sessionIdOffset, 0);
  }

  static endGroupSessionRequest(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createGroupSessionRequest(
    builder: flatbuffers.Builder,
    groupIdOffset: flatbuffers.Offset,
    sessionIdOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    GroupSessionRequest.startGroupSessionRequest(builder);
    GroupSessionRequest.addGroupId(builder, groupIdOffset);
    GroupSessionRequest.addSessionId(builder, sessionIdOffset);
    return GroupSessionRequest.endGroupSessionRequest(builder);
  }
}
