// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ServerHello {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): ServerHello {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsServerHello(bb: flatbuffers.ByteBuffer, obj?: ServerHello): ServerHello {
    return (obj || new ServerHello()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  static getSizePrefixedRootAsServerHello(
    bb: flatbuffers.ByteBuffer,
    obj?: ServerHello
  ): ServerHello {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new ServerHello()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
  }

  heartbeatIntervalMs(): number {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
  }

  ratelimitMessagesPerSec(): number {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
  }

  ratelimitMessagesPerMin(): number {
    const offset = this.bb!.__offset(this.bb_pos, 8);
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
  }

  ratelimitBytesPerSec(): number {
    const offset = this.bb!.__offset(this.bb_pos, 10);
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
  }

  ratelimitBytesPerMin(): number {
    const offset = this.bb!.__offset(this.bb_pos, 12);
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
  }

  static startServerHello(builder: flatbuffers.Builder) {
    builder.startObject(5);
  }

  static addHeartbeatIntervalMs(builder: flatbuffers.Builder, heartbeatIntervalMs: number) {
    builder.addFieldInt32(0, heartbeatIntervalMs, 0);
  }

  static addRatelimitMessagesPerSec(builder: flatbuffers.Builder, ratelimitMessagesPerSec: number) {
    builder.addFieldInt32(1, ratelimitMessagesPerSec, 0);
  }

  static addRatelimitMessagesPerMin(builder: flatbuffers.Builder, ratelimitMessagesPerMin: number) {
    builder.addFieldInt32(2, ratelimitMessagesPerMin, 0);
  }

  static addRatelimitBytesPerSec(builder: flatbuffers.Builder, ratelimitBytesPerSec: number) {
    builder.addFieldInt32(3, ratelimitBytesPerSec, 0);
  }

  static addRatelimitBytesPerMin(builder: flatbuffers.Builder, ratelimitBytesPerMin: number) {
    builder.addFieldInt32(4, ratelimitBytesPerMin, 0);
  }

  static endServerHello(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createServerHello(
    builder: flatbuffers.Builder,
    heartbeatIntervalMs: number,
    ratelimitMessagesPerSec: number,
    ratelimitMessagesPerMin: number,
    ratelimitBytesPerSec: number,
    ratelimitBytesPerMin: number
  ): flatbuffers.Offset {
    ServerHello.startServerHello(builder);
    ServerHello.addHeartbeatIntervalMs(builder, heartbeatIntervalMs);
    ServerHello.addRatelimitMessagesPerSec(builder, ratelimitMessagesPerSec);
    ServerHello.addRatelimitMessagesPerMin(builder, ratelimitMessagesPerMin);
    ServerHello.addRatelimitBytesPerSec(builder, ratelimitBytesPerSec);
    ServerHello.addRatelimitBytesPerMin(builder, ratelimitBytesPerMin);
    return ServerHello.endServerHello(builder);
  }
}
