// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum UserRelationType {
  none = 0,
  friend_request_sent = 1,
  friend_request_received = 2,
  friend = 3,
  blocked = 4,
}
