// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum UserOnlineStatus {
  offline = 0,
  do_not_disturb = 1,
  inactive = 2,
  online = 3,
}
