// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { UserRelationType } from '../../fbs/server/user-relation-type.js';
import * as flatbuffers from 'flatbuffers';

export class UserRelationTypeChanged {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): UserRelationTypeChanged {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsUserRelationTypeChanged(
    bb: flatbuffers.ByteBuffer,
    obj?: UserRelationTypeChanged
  ): UserRelationTypeChanged {
    return (obj || new UserRelationTypeChanged()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsUserRelationTypeChanged(
    bb: flatbuffers.ByteBuffer,
    obj?: UserRelationTypeChanged
  ): UserRelationTypeChanged {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new UserRelationTypeChanged()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  userId(): string | null;
  userId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  userId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  relationType(): UserRelationType {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.readInt8(this.bb_pos + offset) : UserRelationType.none;
  }

  static startUserRelationTypeChanged(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addUserId(builder: flatbuffers.Builder, userIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, userIdOffset, 0);
  }

  static addRelationType(builder: flatbuffers.Builder, relationType: UserRelationType) {
    builder.addFieldInt8(1, relationType, UserRelationType.none);
  }

  static endUserRelationTypeChanged(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createUserRelationTypeChanged(
    builder: flatbuffers.Builder,
    userIdOffset: flatbuffers.Offset,
    relationType: UserRelationType
  ): flatbuffers.Offset {
    UserRelationTypeChanged.startUserRelationTypeChanged(builder);
    UserRelationTypeChanged.addUserId(builder, userIdOffset);
    UserRelationTypeChanged.addRelationType(builder, relationType);
    return UserRelationTypeChanged.endUserRelationTypeChanged(builder);
  }
}
