// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class UserSessionRequest {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): UserSessionRequest {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsUserSessionRequest(
    bb: flatbuffers.ByteBuffer,
    obj?: UserSessionRequest
  ): UserSessionRequest {
    return (obj || new UserSessionRequest()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsUserSessionRequest(
    bb: flatbuffers.ByteBuffer,
    obj?: UserSessionRequest
  ): UserSessionRequest {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new UserSessionRequest()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  userId(): string | null;
  userId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  userId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  sessionId(): string | null;
  sessionId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  sessionId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  static startUserSessionRequest(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addUserId(builder: flatbuffers.Builder, userIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, userIdOffset, 0);
  }

  static addSessionId(builder: flatbuffers.Builder, sessionIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, sessionIdOffset, 0);
  }

  static endUserSessionRequest(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createUserSessionRequest(
    builder: flatbuffers.Builder,
    userIdOffset: flatbuffers.Offset,
    sessionIdOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    UserSessionRequest.startUserSessionRequest(builder);
    UserSessionRequest.addUserId(builder, userIdOffset);
    UserSessionRequest.addSessionId(builder, sessionIdOffset);
    return UserSessionRequest.endUserSessionRequest(builder);
  }
}
