// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { UserOnlineStatus } from '../../fbs/server/user-online-status.js';
import * as flatbuffers from 'flatbuffers';

export class UserOnlineStatusChanged {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): UserOnlineStatusChanged {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsUserOnlineStatusChanged(
    bb: flatbuffers.ByteBuffer,
    obj?: UserOnlineStatusChanged
  ): UserOnlineStatusChanged {
    return (obj || new UserOnlineStatusChanged()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsUserOnlineStatusChanged(
    bb: flatbuffers.ByteBuffer,
    obj?: UserOnlineStatusChanged
  ): UserOnlineStatusChanged {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new UserOnlineStatusChanged()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  userId(): string | null;
  userId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  userId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  onlineStatus(): UserOnlineStatus {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.readInt8(this.bb_pos + offset) : UserOnlineStatus.offline;
  }

  static startUserOnlineStatusChanged(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addUserId(builder: flatbuffers.Builder, userIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, userIdOffset, 0);
  }

  static addOnlineStatus(builder: flatbuffers.Builder, onlineStatus: UserOnlineStatus) {
    builder.addFieldInt8(1, onlineStatus, UserOnlineStatus.offline);
  }

  static endUserOnlineStatusChanged(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createUserOnlineStatusChanged(
    builder: flatbuffers.Builder,
    userIdOffset: flatbuffers.Offset,
    onlineStatus: UserOnlineStatus
  ): flatbuffers.Offset {
    UserOnlineStatusChanged.startUserOnlineStatusChanged(builder);
    UserOnlineStatusChanged.addUserId(builder, userIdOffset);
    UserOnlineStatusChanged.addOnlineStatus(builder, onlineStatus);
    return UserOnlineStatusChanged.endUserOnlineStatusChanged(builder);
  }
}
