// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class SessionIceCandidateDiscovered {
  bb: flatbuffers.ByteBuffer | null = null;
  bb_pos = 0;
  __init(i: number, bb: flatbuffers.ByteBuffer): SessionIceCandidateDiscovered {
    this.bb_pos = i;
    this.bb = bb;
    return this;
  }

  static getRootAsSessionIceCandidateDiscovered(
    bb: flatbuffers.ByteBuffer,
    obj?: SessionIceCandidateDiscovered
  ): SessionIceCandidateDiscovered {
    return (obj || new SessionIceCandidateDiscovered()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  static getSizePrefixedRootAsSessionIceCandidateDiscovered(
    bb: flatbuffers.ByteBuffer,
    obj?: SessionIceCandidateDiscovered
  ): SessionIceCandidateDiscovered {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
    return (obj || new SessionIceCandidateDiscovered()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb
    );
  }

  sessionId(): string | null;
  sessionId(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  sessionId(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  candidate(): string | null;
  candidate(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
  candidate(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 6);
    return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
  }

  static startSessionIceCandidateDiscovered(builder: flatbuffers.Builder) {
    builder.startObject(2);
  }

  static addSessionId(builder: flatbuffers.Builder, sessionIdOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, sessionIdOffset, 0);
  }

  static addCandidate(builder: flatbuffers.Builder, candidateOffset: flatbuffers.Offset) {
    builder.addFieldOffset(1, candidateOffset, 0);
  }

  static endSessionIceCandidateDiscovered(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject();
    return offset;
  }

  static createSessionIceCandidateDiscovered(
    builder: flatbuffers.Builder,
    sessionIdOffset: flatbuffers.Offset,
    candidateOffset: flatbuffers.Offset
  ): flatbuffers.Offset {
    SessionIceCandidateDiscovered.startSessionIceCandidateDiscovered(builder);
    SessionIceCandidateDiscovered.addSessionId(builder, sessionIdOffset);
    SessionIceCandidateDiscovered.addCandidate(builder, candidateOffset);
    return SessionIceCandidateDiscovered.endSessionIceCandidateDiscovered(builder);
  }
}
