/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeviceDto,
  ErrorDetails,
} from '../models';
import {
    DeviceDtoFromJSON,
    DeviceDtoToJSON,
    ErrorDetailsFromJSON,
    ErrorDetailsToJSON,
} from '../models';

export interface GetDeviceByIdRequest {
    deviceId: string;
}

/**
 * DeviceApi - interface
 * 
 * @export
 * @interface DeviceApiInterface
 */
export interface DeviceApiInterface {
    /**
     * 
     * @summary 
     * @param {string} deviceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceApiInterface
     */
    getDeviceByIdRaw(requestParameters: GetDeviceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceDto>>;

    /**
     * 
     */
    getDeviceById(deviceId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceDto>;

}

/**
 * 
 */
export class DeviceApi extends runtime.BaseAPI implements DeviceApiInterface {

    /**
     * 
     */
    async getDeviceByIdRaw(requestParameters: GetDeviceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceDto>> {
        if (requestParameters.deviceId === null || requestParameters.deviceId === undefined) {
            throw new runtime.RequiredError('deviceId','Required parameter requestParameters.deviceId was null or undefined when calling getDeviceById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/device/{deviceId}`.replace(`{${"deviceId"}}`, encodeURIComponent(String(requestParameters.deviceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceDtoFromJSON(jsonValue));
    }

    /**
     * 
     */
    async getDeviceById(deviceId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceDto> {
        const response = await this.getDeviceByIdRaw({ deviceId: deviceId }, initOverrides);
        return await response.value();
    }

}
