/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorDetails,
  ProviderDataDto,
} from '../models';
import {
    ErrorDetailsFromJSON,
    ErrorDetailsToJSON,
    ProviderDataDtoFromJSON,
    ProviderDataDtoToJSON,
} from '../models';

export interface SSOAuthenticateRequest {
    providerName: string;
}

export interface SSOCallbackRequest {
    providerName: string;
}

export interface SSOGetProviderDataRequest {
    ssoToken?: string;
}

/**
 * SingleSignOnApi - interface
 * 
 * @export
 * @interface SingleSignOnApiInterface
 */
export interface SingleSignOnApiInterface {
    /**
     * 
     * @summary Warning:  This endpoint is not meant to be called by a 3rd party, it will redirect the request for OAuth authentication with the specified provider.  It is documented here for transparency, and to automatically generate the OpenAPI client for the frontend.
     * @param {string} providerName Name of the SSO provider to use, supported providers can be fetched from /api/v1/sso/providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SingleSignOnApiInterface
     */
    sSOAuthenticateRaw(requestParameters: SSOAuthenticateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Warning:  This endpoint is not meant to be called by a 3rd party, it will redirect the request for OAuth authentication with the specified provider.  It is documented here for transparency, and to automatically generate the OpenAPI client for the frontend.
     */
    sSOAuthenticate(providerName: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Warning:  This endpoint is not meant to be called by a 3rd party, it will redirect the request for OAuth authentication with the specified provider.  It is documented here for transparency, and to automatically generate the OpenAPI client for the frontend.
     * @param {string} providerName Name of the SSO provider to use, supported providers can be fetched from /api/v1/sso/providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SingleSignOnApiInterface
     */
    sSOCallbackRaw(requestParameters: SSOCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Warning:  This endpoint is not meant to be called by a 3rd party, it will redirect the request for OAuth authentication with the specified provider.  It is documented here for transparency, and to automatically generate the OpenAPI client for the frontend.
     */
    sSOCallback(providerName: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Returns the data supplied by the SSO provider
     * @param {string} [ssoToken] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SingleSignOnApiInterface
     */
    sSOGetProviderDataRaw(requestParameters: SSOGetProviderDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderDataDto>>;

    /**
     * Returns the data supplied by the SSO provider
     */
    sSOGetProviderData(ssoToken?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderDataDto>;

    /**
     * 
     * @summary Returns a list of supported SSO providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SingleSignOnApiInterface
     */
    sSOListProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * Returns a list of supported SSO providers
     */
    sSOListProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

}

/**
 * 
 */
export class SingleSignOnApi extends runtime.BaseAPI implements SingleSignOnApiInterface {

    /**
     * Warning:  This endpoint is not meant to be called by a 3rd party, it will redirect the request for OAuth authentication with the specified provider.  It is documented here for transparency, and to automatically generate the OpenAPI client for the frontend.
     */
    async sSOAuthenticateRaw(requestParameters: SSOAuthenticateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.providerName === null || requestParameters.providerName === undefined) {
            throw new runtime.RequiredError('providerName','Required parameter requestParameters.providerName was null or undefined when calling sSOAuthenticate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/sso/{providerName}`.replace(`{${"providerName"}}`, encodeURIComponent(String(requestParameters.providerName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Warning:  This endpoint is not meant to be called by a 3rd party, it will redirect the request for OAuth authentication with the specified provider.  It is documented here for transparency, and to automatically generate the OpenAPI client for the frontend.
     */
    async sSOAuthenticate(providerName: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sSOAuthenticateRaw({ providerName: providerName }, initOverrides);
    }

    /**
     * Warning:  This endpoint is not meant to be called by a 3rd party, it will redirect the request for OAuth authentication with the specified provider.  It is documented here for transparency, and to automatically generate the OpenAPI client for the frontend.
     */
    async sSOCallbackRaw(requestParameters: SSOCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.providerName === null || requestParameters.providerName === undefined) {
            throw new runtime.RequiredError('providerName','Required parameter requestParameters.providerName was null or undefined when calling sSOCallback.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/sso/{providerName}/callback`.replace(`{${"providerName"}}`, encodeURIComponent(String(requestParameters.providerName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Warning:  This endpoint is not meant to be called by a 3rd party, it will redirect the request for OAuth authentication with the specified provider.  It is documented here for transparency, and to automatically generate the OpenAPI client for the frontend.
     */
    async sSOCallback(providerName: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sSOCallbackRaw({ providerName: providerName }, initOverrides);
    }

    /**
     * Returns the data supplied by the SSO provider
     */
    async sSOGetProviderDataRaw(requestParameters: SSOGetProviderDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderDataDto>> {
        const queryParameters: any = {};

        if (requestParameters.ssoToken !== undefined) {
            queryParameters['ssoToken'] = requestParameters.ssoToken;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/sso/providerdata`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderDataDtoFromJSON(jsonValue));
    }

    /**
     * Returns the data supplied by the SSO provider
     */
    async sSOGetProviderData(ssoToken?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderDataDto> {
        const response = await this.sSOGetProviderDataRaw({ ssoToken: ssoToken }, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of supported SSO providers
     */
    async sSOListProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/sso/providers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns a list of supported SSO providers
     */
    async sSOListProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.sSOListProvidersRaw(initOverrides);
        return await response.value();
    }

}
