/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * WebSocketApi - interface
 * 
 * @export
 * @interface WebSocketApiInterface
 */
export interface WebSocketApiInterface {
    /**
     * 
     * @summary Websocket endpoint for pub/sub communication (e.g. chat, notifications, events)    Documentation:  Yes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebSocketApiInterface
     */
    wsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Websocket endpoint for pub/sub communication (e.g. chat, notifications, events)    Documentation:  Yes
     */
    wsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class WebSocketApi extends runtime.BaseAPI implements WebSocketApiInterface {

    /**
     * Websocket endpoint for pub/sub communication (e.g. chat, notifications, events)    Documentation:  Yes
     */
    async wsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ws`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Websocket endpoint for pub/sub communication (e.g. chat, notifications, events)    Documentation:  Yes
     */
    async wsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.wsGetRaw(initOverrides);
    }

}
