/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorDetails,
} from '../models';
import {
    ErrorDetailsFromJSON,
    ErrorDetailsToJSON,
} from '../models';

export interface WebSocketRequest {
    token?: string;
}

/**
 * WebSocketApi - interface
 * 
 * @export
 * @interface WebSocketApiInterface
 */
export interface WebSocketApiInterface {
    /**
     * 
     * @summary Websocket endpoint for pub/sub communication (e.g. chat, notifications, events)    Documentation:  Yes
     * @param {string} [token] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebSocketApiInterface
     */
    webSocketRaw(requestParameters: WebSocketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Websocket endpoint for pub/sub communication (e.g. chat, notifications, events)    Documentation:  Yes
     */
    webSocket(token?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class WebSocketApi extends runtime.BaseAPI implements WebSocketApiInterface {

    /**
     * Websocket endpoint for pub/sub communication (e.g. chat, notifications, events)    Documentation:  Yes
     */
    async webSocketRaw(requestParameters: WebSocketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters.token !== undefined) {
            queryParameters['token'] = requestParameters.token;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/ws`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Websocket endpoint for pub/sub communication (e.g. chat, notifications, events)    Documentation:  Yes
     */
    async webSocket(token?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webSocketRaw({ token: token }, initOverrides);
    }

}
