/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * If the account was created using OAuth and in a way that ensures the email address is valid, a session will be created and returned here
 * @export
 * @interface AccountCreateOkResponseDtoSession
 */
export interface AccountCreateOkResponseDtoSession {
    /**
     * 
     * @type {string}
     * @memberof AccountCreateOkResponseDtoSession
     */
    jwtToken: string;
}

/**
 * Check if a given object implements the AccountCreateOkResponseDtoSession interface.
 */
export function instanceOfAccountCreateOkResponseDtoSession(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "jwtToken" in value;

    return isInstance;
}

export function AccountCreateOkResponseDtoSessionFromJSON(json: any): AccountCreateOkResponseDtoSession {
    return AccountCreateOkResponseDtoSessionFromJSONTyped(json, false);
}

export function AccountCreateOkResponseDtoSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCreateOkResponseDtoSession {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jwtToken': json['jwtToken'],
    };
}

export function AccountCreateOkResponseDtoSessionToJSON(value?: AccountCreateOkResponseDtoSession | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jwtToken': value.jwtToken,
    };
}

