/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request sent to server to request a password reset token
 * @export
 * @interface AccountRecoveryRequestRequest
 */
export interface AccountRecoveryRequestRequest {
    /**
     * Email of your account you want to recover
     * @type {string}
     * @memberof AccountRecoveryRequestRequest
     */
    email: string;
    /**
     * Response from cloudflare turnstile request
     * @type {string}
     * @memberof AccountRecoveryRequestRequest
     */
    turnstileResponse: string;
}

/**
 * Check if a given object implements the AccountRecoveryRequestRequest interface.
 */
export function instanceOfAccountRecoveryRequestRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "turnstileResponse" in value;

    return isInstance;
}

export function AccountRecoveryRequestRequestFromJSON(json: any): AccountRecoveryRequestRequest {
    return AccountRecoveryRequestRequestFromJSONTyped(json, false);
}

export function AccountRecoveryRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRecoveryRequestRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'turnstileResponse': json['turnstileResponse'],
    };
}

export function AccountRecoveryRequestRequestToJSON(value?: AccountRecoveryRequestRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'turnstileResponse': value.turnstileResponse,
    };
}

