/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request sent to server to add a oauth connection to a account
 * @export
 * @interface AddOAuthProviderRequest
 */
export interface AddOAuthProviderRequest {
    /**
     * 
     * @type {string}
     * @memberof AddOAuthProviderRequest
     */
    oauthCode: string;
}

/**
 * Check if a given object implements the AddOAuthProviderRequest interface.
 */
export function instanceOfAddOAuthProviderRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "oauthCode" in value;

    return isInstance;
}

export function AddOAuthProviderRequestFromJSON(json: any): AddOAuthProviderRequest {
    return AddOAuthProviderRequestFromJSONTyped(json, false);
}

export function AddOAuthProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOAuthProviderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oauthCode': json['oauthCode'],
    };
}

export function AddOAuthProviderRequestToJSON(value?: AddOAuthProviderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'oauthCode': value.oauthCode,
    };
}

