/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiConfigDisabledFeatures } from './ApiConfigDisabledFeatures';
import {
    ApiConfigDisabledFeaturesFromJSON,
    ApiConfigDisabledFeaturesFromJSONTyped,
    ApiConfigDisabledFeaturesToJSON,
} from './ApiConfigDisabledFeatures';

/**
 * 
 * @export
 * @interface ApiConfig
 */
export interface ApiConfig {
    /**
     * 
     * @type {ApiConfigDisabledFeatures}
     * @memberof ApiConfig
     */
    disabledFeatures: ApiConfigDisabledFeatures;
}

/**
 * Check if a given object implements the ApiConfig interface.
 */
export function instanceOfApiConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "disabledFeatures" in value;

    return isInstance;
}

export function ApiConfigFromJSON(json: any): ApiConfig {
    return ApiConfigFromJSONTyped(json, false);
}

export function ApiConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disabledFeatures': ApiConfigDisabledFeaturesFromJSON(json['disabledFeatures']),
    };
}

export function ApiConfigToJSON(value?: ApiConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disabledFeatures': ApiConfigDisabledFeaturesToJSON(value.disabledFeatures),
    };
}

