/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * WebRTC configuration
 * @export
 * @interface ApiConfigWebRtc
 */
export interface ApiConfigWebRtc {
    /**
     * 
     * @type {boolean}
     * @memberof ApiConfigWebRtc
     */
    enabled: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiConfigWebRtc
     */
    approvedStunServers: Array<string>;
}

/**
 * Check if a given object implements the ApiConfigWebRtc interface.
 */
export function instanceOfApiConfigWebRtc(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enabled" in value;
    isInstance = isInstance && "approvedStunServers" in value;

    return isInstance;
}

export function ApiConfigWebRtcFromJSON(json: any): ApiConfigWebRtc {
    return ApiConfigWebRtcFromJSONTyped(json, false);
}

export function ApiConfigWebRtcFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiConfigWebRtc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'approvedStunServers': json['approvedStunServers'],
    };
}

export function ApiConfigWebRtcToJSON(value?: ApiConfigWebRtc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'approvedStunServers': value.approvedStunServers,
    };
}

