/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDisabledFeatures
 */
export interface ApiDisabledFeatures {
    /**
     * If true, WebRTC is disabled
     * @type {boolean}
     * @memberof ApiDisabledFeatures
     */
    webrtc?: boolean;
    /**
     * If true, WebSockets are disabled
     * @type {boolean}
     * @memberof ApiDisabledFeatures
     */
    websockets?: boolean;
    /**
     * List of disabled endpoints, if an endpoint is in this list, it will return a "503 Service Unavailable"
     * @type {Array<string>}
     * @memberof ApiDisabledFeatures
     */
    endpoints?: Array<string>;
}

/**
 * Check if a given object implements the ApiDisabledFeatures interface.
 */
export function instanceOfApiDisabledFeatures(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiDisabledFeaturesFromJSON(json: any): ApiDisabledFeatures {
    return ApiDisabledFeaturesFromJSONTyped(json, false);
}

export function ApiDisabledFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDisabledFeatures {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'webrtc': !exists(json, 'webrtc') ? undefined : json['webrtc'],
        'websockets': !exists(json, 'websockets') ? undefined : json['websockets'],
        'endpoints': !exists(json, 'endpoints') ? undefined : json['endpoints'],
    };
}

export function ApiDisabledFeaturesToJSON(value?: ApiDisabledFeatures | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'webrtc': value.webrtc,
        'websockets': value.websockets,
        'endpoints': value.endpoints,
    };
}

