/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationConfig
 */
export interface AuthenticationConfig {
    /**
     * Google Client ID for OAuth, if null, Google login will be disabled
     * @type {string}
     * @memberof AuthenticationConfig
     */
    googleClientId?: string | null;
    /**
     * Github Client ID for OAuth, if null, Github login will be disabled
     * @type {string}
     * @memberof AuthenticationConfig
     */
    githubClientId?: string | null;
    /**
     * ReCaptcha Client ID for bot detection, if null, ReCaptcha will be disabled
     * @type {string}
     * @memberof AuthenticationConfig
     */
    recaptchaSiteKey?: string | null;
}

/**
 * Check if a given object implements the AuthenticationConfig interface.
 */
export function instanceOfAuthenticationConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthenticationConfigFromJSON(json: any): AuthenticationConfig {
    return AuthenticationConfigFromJSONTyped(json, false);
}

export function AuthenticationConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'googleClientId': !exists(json, 'google_client_id') ? undefined : json['google_client_id'],
        'githubClientId': !exists(json, 'github_client_id') ? undefined : json['github_client_id'],
        'recaptchaSiteKey': !exists(json, 'recaptcha_site_key') ? undefined : json['recaptcha_site_key'],
    };
}

export function AuthenticationConfigToJSON(value?: AuthenticationConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'google_client_id': value.googleClientId,
        'github_client_id': value.githubClientId,
        'recaptcha_site_key': value.recaptchaSiteKey,
    };
}

