/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteOAuthAccountCreationRequest
 */
export interface CompleteOAuthAccountCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof CompleteOAuthAccountCreationRequest
     */
    oAuthTicket: string;
    /**
     * 
     * @type {number}
     * @memberof CompleteOAuthAccountCreationRequest
     */
    acceptedPrivacyPolicyVersion: number;
    /**
     * 
     * @type {number}
     * @memberof CompleteOAuthAccountCreationRequest
     */
    acceptedTermsOfServiceVersion: number;
    /**
     * 
     * @type {string}
     * @memberof CompleteOAuthAccountCreationRequest
     */
    password: string;
}

/**
 * Check if a given object implements the CompleteOAuthAccountCreationRequest interface.
 */
export function instanceOfCompleteOAuthAccountCreationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "oAuthTicket" in value;
    isInstance = isInstance && "acceptedPrivacyPolicyVersion" in value;
    isInstance = isInstance && "acceptedTermsOfServiceVersion" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function CompleteOAuthAccountCreationRequestFromJSON(json: any): CompleteOAuthAccountCreationRequest {
    return CompleteOAuthAccountCreationRequestFromJSONTyped(json, false);
}

export function CompleteOAuthAccountCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteOAuthAccountCreationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oAuthTicket': json['oAuthTicket'],
        'acceptedPrivacyPolicyVersion': json['acceptedPrivacyPolicyVersion'],
        'acceptedTermsOfServiceVersion': json['acceptedTermsOfServiceVersion'],
        'password': json['password'],
    };
}

export function CompleteOAuthAccountCreationRequestToJSON(value?: CompleteOAuthAccountCreationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'oAuthTicket': value.oAuthTicket,
        'acceptedPrivacyPolicyVersion': value.acceptedPrivacyPolicyVersion,
        'acceptedTermsOfServiceVersion': value.acceptedTermsOfServiceVersion,
        'password': value.password,
    };
}

