/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactConfig
 */
export interface ContactConfig {
    /**
     * 
     * @type {string}
     * @memberof ContactConfig
     */
    support?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactConfig
     */
    contact?: string;
}

/**
 * Check if a given object implements the ContactConfig interface.
 */
export function instanceOfContactConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ContactConfigFromJSON(json: any): ContactConfig {
    return ContactConfigFromJSONTyped(json, false);
}

export function ContactConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'support': !exists(json, 'support') ? undefined : json['support'],
        'contact': !exists(json, 'contact') ? undefined : json['contact'],
    };
}

export function ContactConfigToJSON(value?: ContactConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'support': value.support,
        'contact': value.contact,
    };
}

