/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOk
 */
export interface CreateOk {
    /**
     * 
     * @type {string}
     * @memberof CreateOk
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOk
     */
    message: string;
}

/**
 * Check if a given object implements the CreateOk interface.
 */
export function instanceOfCreateOk(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function CreateOkFromJSON(json: any): CreateOk {
    return CreateOkFromJSONTyped(json, false);
}

export function CreateOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
    };
}

export function CreateOkToJSON(value?: CreateOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'message': value.message,
    };
}

