/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Message sent to server to create a new account
 * @export
 * @interface CreateAccountRequest
 */
export interface CreateAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAccountRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAccountRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAccountRequest
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAccountRequest
     */
    acceptedPrivacyPolicyVersion: number;
    /**
     * 
     * @type {number}
     * @memberof CreateAccountRequest
     */
    acceptedTermsOfServiceVersion: number;
    /**
     * Response from cloudflare turnstile request
     * @type {string}
     * @memberof CreateAccountRequest
     */
    turnstileResponse: string;
}

/**
 * Check if a given object implements the CreateAccountRequest interface.
 */
export function instanceOfCreateAccountRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "acceptedPrivacyPolicyVersion" in value;
    isInstance = isInstance && "acceptedTermsOfServiceVersion" in value;
    isInstance = isInstance && "turnstileResponse" in value;

    return isInstance;
}

export function CreateAccountRequestFromJSON(json: any): CreateAccountRequest {
    return CreateAccountRequestFromJSONTyped(json, false);
}

export function CreateAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'email': json['email'],
        'acceptedPrivacyPolicyVersion': json['acceptedPrivacyPolicyVersion'],
        'acceptedTermsOfServiceVersion': json['acceptedTermsOfServiceVersion'],
        'turnstileResponse': json['turnstileResponse'],
    };
}

export function CreateAccountRequestToJSON(value?: CreateAccountRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'email': value.email,
        'acceptedPrivacyPolicyVersion': value.acceptedPrivacyPolicyVersion,
        'acceptedTermsOfServiceVersion': value.acceptedTermsOfServiceVersion,
        'turnstileResponse': value.turnstileResponse,
    };
}

