/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceDto
 */
export interface DeviceDto {
    /**
     * 
     * @type {string}
     * @memberof DeviceDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof DeviceDto
     */
    registeredAt: Date;
}

/**
 * Check if a given object implements the DeviceDto interface.
 */
export function instanceOfDeviceDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "registeredAt" in value;

    return isInstance;
}

export function DeviceDtoFromJSON(json: any): DeviceDto {
    return DeviceDtoFromJSONTyped(json, false);
}

export function DeviceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'registeredAt': (new Date(json['registeredAt'])),
    };
}

export function DeviceDtoToJSON(value?: DeviceDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'registeredAt': (value.registeredAt.toISOString()),
    };
}

