/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorDetailsNotification } from './ErrorDetailsNotification';
import {
    ErrorDetailsNotificationFromJSON,
    ErrorDetailsNotificationFromJSONTyped,
    ErrorDetailsNotificationToJSON,
} from './ErrorDetailsNotification';

/**
 * Details about the error
 * @export
 * @interface ErrorDetails
 */
export interface ErrorDetails {
    /**
     * Error code, this is a short string that can be used to identify the error (meant for developers)
     * @type {string}
     * @memberof ErrorDetails
     */
    code: string;
    /**
     * Detailed description of what this error is about (meant for developers)
     * @type {string}
     * @memberof ErrorDetails
     */
    detail: string;
    /**
     * Suggestion on how to midegate this error (meant for developers)
     * @type {string}
     * @memberof ErrorDetails
     */
    suggestion?: string | null;
    /**
     * Errors for specific fields in the request
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ErrorDetails
     */
    fields?: { [key: string]: Array<string>; } | null;
    /**
     * 
     * @type {ErrorDetailsNotification}
     * @memberof ErrorDetails
     */
    notification?: ErrorDetailsNotification | null;
}

/**
 * Check if a given object implements the ErrorDetails interface.
 */
export function instanceOfErrorDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "detail" in value;

    return isInstance;
}

export function ErrorDetailsFromJSON(json: any): ErrorDetails {
    return ErrorDetailsFromJSONTyped(json, false);
}

export function ErrorDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
        'suggestion': !exists(json, 'suggestion') ? undefined : json['suggestion'],
        'fields': !exists(json, 'fields') ? undefined : json['fields'],
        'notification': !exists(json, 'notification') ? undefined : ErrorDetailsNotificationFromJSON(json['notification']),
    };
}

export function ErrorDetailsToJSON(value?: ErrorDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'detail': value.detail,
        'suggestion': value.suggestion,
        'fields': value.fields,
        'notification': ErrorDetailsNotificationToJSON(value.notification),
    };
}

