/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OAuthResultType {
    signedIn = 'signedIn',
    requireTwoFactor = 'requireTwoFactor',
    requireAccountCreation = 'requireAccountCreation'
}


export function OAuthResultTypeFromJSON(json: any): OAuthResultType {
    return OAuthResultTypeFromJSONTyped(json, false);
}

export function OAuthResultTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthResultType {
    return json as OAuthResultType;
}

export function OAuthResultTypeToJSON(value?: OAuthResultType | null): any {
    return value as any;
}

