/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthProviderList
 */
export interface OAuthProviderList {
    /**
     * 
     * @type {Array<string>}
     * @memberof OAuthProviderList
     */
    providers?: Array<string>;
}

/**
 * Check if a given object implements the OAuthProviderList interface.
 */
export function instanceOfOAuthProviderList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OAuthProviderListFromJSON(json: any): OAuthProviderList {
    return OAuthProviderListFromJSONTyped(json, false);
}

export function OAuthProviderListFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthProviderList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'providers': !exists(json, 'providers') ? undefined : json['providers'],
    };
}

export function OAuthProviderListToJSON(value?: OAuthProviderList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'providers': value.providers,
    };
}

