/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request sent to server to request a password reset token
 * @export
 * @interface RecoveryRequest
 */
export interface RecoveryRequest {
    /**
     * Email of your account you want to recover
     * @type {string}
     * @memberof RecoveryRequest
     */
    email?: string;
    /**
     * Response from google recaptcha request
     * @type {string}
     * @memberof RecoveryRequest
     */
    recaptchaResponse?: string;
}

/**
 * Check if a given object implements the RecoveryRequest interface.
 */
export function instanceOfRecoveryRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryRequestFromJSON(json: any): RecoveryRequest {
    return RecoveryRequestFromJSONTyped(json, false);
}

export function RecoveryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'recaptchaResponse': !exists(json, 'recaptcha_response') ? undefined : json['recaptcha_response'],
    };
}

export function RecoveryRequestToJSON(value?: RecoveryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'recaptcha_response': value.recaptchaResponse,
    };
}

