/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request sent to server to commit a password reset
 * @export
 * @interface RecoveryConfirm
 */
export interface RecoveryConfirm {
    /**
     * The new password to set
     * @type {string}
     * @memberof RecoveryConfirm
     */
    newPassword?: string;
    /**
     * The token sent to the user's email address
     * @type {string}
     * @memberof RecoveryConfirm
     */
    token?: string;
}

/**
 * Check if a given object implements the RecoveryConfirm interface.
 */
export function instanceOfRecoveryConfirm(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecoveryConfirmFromJSON(json: any): RecoveryConfirm {
    return RecoveryConfirmFromJSONTyped(json, false);
}

export function RecoveryConfirmFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryConfirm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newPassword': !exists(json, 'new_password') ? undefined : json['new_password'],
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function RecoveryConfirmToJSON(value?: RecoveryConfirm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'new_password': value.newPassword,
        'token': value.token,
    };
}

