/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionDto
 */
export interface SessionDto {
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof SessionDto
     */
    issuedAtUtc: Date;
    /**
     * 
     * @type {Date}
     * @memberof SessionDto
     */
    expiresAtUtc: Date;
}

/**
 * Check if a given object implements the SessionDto interface.
 */
export function instanceOfSessionDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "issuedAtUtc" in value;
    isInstance = isInstance && "expiresAtUtc" in value;

    return isInstance;
}

export function SessionDtoFromJSON(json: any): SessionDto {
    return SessionDtoFromJSONTyped(json, false);
}

export function SessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'issuedAtUtc': (new Date(json['issuedAtUtc'])),
        'expiresAtUtc': (new Date(json['expiresAtUtc'])),
    };
}

export function SessionDtoToJSON(value?: SessionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'issuedAtUtc': (value.issuedAtUtc.toISOString()),
        'expiresAtUtc': (value.expiresAtUtc.toISOString()),
    };
}

