/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SeverityLevel = {
    info: 'info',
    warning: 'warning',
    error: 'error'
} as const;
export type SeverityLevel = typeof SeverityLevel[keyof typeof SeverityLevel];


export function SeverityLevelFromJSON(json: any): SeverityLevel {
    return SeverityLevelFromJSONTyped(json, false);
}

export function SeverityLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeverityLevel {
    return json as SeverityLevel;
}

export function SeverityLevelToJSON(value?: SeverityLevel | null): any {
    return value as any;
}

