/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountDto } from './AccountDto';
import {
    AccountDtoFromJSON,
    AccountDtoFromJSONTyped,
    AccountDtoToJSON,
} from './AccountDto';
import type { SessionDto } from './SessionDto';
import {
    SessionDtoFromJSON,
    SessionDtoFromJSONTyped,
    SessionDtoToJSON,
} from './SessionDto';

/**
 * 
 * @export
 * @interface SignInOk
 */
export interface SignInOk {
    /**
     * 
     * @type {SessionDto}
     * @memberof SignInOk
     */
    session?: SessionDto;
    /**
     * 
     * @type {AccountDto}
     * @memberof SignInOk
     */
    account?: AccountDto;
}

/**
 * Check if a given object implements the SignInOk interface.
 */
export function instanceOfSignInOk(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SignInOkFromJSON(json: any): SignInOk {
    return SignInOkFromJSONTyped(json, false);
}

export function SignInOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'session': !exists(json, 'session') ? undefined : SessionDtoFromJSON(json['session']),
        'account': !exists(json, 'account') ? undefined : AccountDtoFromJSON(json['account']),
    };
}

export function SignInOkToJSON(value?: SignInOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'session': SessionDtoToJSON(value.session),
        'account': AccountDtoToJSON(value.account),
    };
}

