/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInOkSession
 */
export interface SignInOkSession {
    /**
     * 
     * @type {string}
     * @memberof SignInOkSession
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof SignInOkSession
     */
    issuedAtUtc: Date;
    /**
     * 
     * @type {Date}
     * @memberof SignInOkSession
     */
    expiresAtUtc: Date;
}

/**
 * Check if a given object implements the SignInOkSession interface.
 */
export function instanceOfSignInOkSession(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "issuedAtUtc" in value;
    isInstance = isInstance && "expiresAtUtc" in value;

    return isInstance;
}

export function SignInOkSessionFromJSON(json: any): SignInOkSession {
    return SignInOkSessionFromJSONTyped(json, false);
}

export function SignInOkSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInOkSession {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'issuedAtUtc': (new Date(json['issuedAtUtc'])),
        'expiresAtUtc': (new Date(json['expiresAtUtc'])),
    };
}

export function SignInOkSessionToJSON(value?: SignInOkSession | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'issuedAtUtc': (value.issuedAtUtc.toISOString()),
        'expiresAtUtc': (value.expiresAtUtc.toISOString()),
    };
}

