/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialsConfig
 */
export interface SocialsConfig {
    /**
     * Uri pointing to a github account
     * @type {string}
     * @memberof SocialsConfig
     */
    githubUri?: string | null;
    /**
     * Uri pointing to a twitter account
     * @type {string}
     * @memberof SocialsConfig
     */
    twitterUri?: string | null;
    /**
     * Uri pointing to a reddit account
     * @type {string}
     * @memberof SocialsConfig
     */
    redditUri?: string | null;
    /**
     * Uri pointing to a personal website
     * @type {string}
     * @memberof SocialsConfig
     */
    websiteUri?: string | null;
}

/**
 * Check if a given object implements the SocialsConfig interface.
 */
export function instanceOfSocialsConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SocialsConfigFromJSON(json: any): SocialsConfig {
    return SocialsConfigFromJSONTyped(json, false);
}

export function SocialsConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialsConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'githubUri': !exists(json, 'githubUri') ? undefined : json['githubUri'],
        'twitterUri': !exists(json, 'twitterUri') ? undefined : json['twitterUri'],
        'redditUri': !exists(json, 'redditUri') ? undefined : json['redditUri'],
        'websiteUri': !exists(json, 'websiteUri') ? undefined : json['websiteUri'],
    };
}

export function SocialsConfigToJSON(value?: SocialsConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'githubUri': value.githubUri,
        'twitterUri': value.twitterUri,
        'redditUri': value.redditUri,
        'websiteUri': value.websiteUri,
    };
}

