/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request sent to server to update account username
 * @export
 * @interface UpdateUserNameRequest
 */
export interface UpdateUserNameRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserNameRequest
     */
    newUsername: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserNameRequest
     */
    password: string;
}

/**
 * Check if a given object implements the UpdateUserNameRequest interface.
 */
export function instanceOfUpdateUserNameRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "newUsername" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UpdateUserNameRequestFromJSON(json: any): UpdateUserNameRequest {
    return UpdateUserNameRequestFromJSONTyped(json, false);
}

export function UpdateUserNameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserNameRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newUsername': json['newUsername'],
        'password': json['password'],
    };
}

export function UpdateUserNameRequestToJSON(value?: UpdateUserNameRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'newUsername': value.newUsername,
        'password': value.password,
    };
}

