/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfilePictureOk
 */
export interface UpdateProfilePictureOk {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfilePictureOk
     */
    imageId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfilePictureOk
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfilePictureOk
     */
    imageHash?: string;
}

/**
 * Check if a given object implements the UpdateProfilePictureOk interface.
 */
export function instanceOfUpdateProfilePictureOk(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateProfilePictureOkFromJSON(json: any): UpdateProfilePictureOk {
    return UpdateProfilePictureOkFromJSONTyped(json, false);
}

export function UpdateProfilePictureOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfilePictureOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageId': !exists(json, 'imageId') ? undefined : json['imageId'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'imageHash': !exists(json, 'imageHash') ? undefined : json['imageHash'],
    };
}

export function UpdateProfilePictureOkToJSON(value?: UpdateProfilePictureOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'imageId': value.imageId,
        'imageUrl': value.imageUrl,
        'imageHash': value.imageHash,
    };
}

