/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request sent to server to update account email address
 * @export
 * @interface UpdateEmailRequest
 */
export interface UpdateEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailRequest
     */
    newEmail: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailRequest
     */
    password: string;
}

/**
 * Check if a given object implements the UpdateEmailRequest interface.
 */
export function instanceOfUpdateEmailRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "newEmail" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UpdateEmailRequestFromJSON(json: any): UpdateEmailRequest {
    return UpdateEmailRequestFromJSONTyped(json, false);
}

export function UpdateEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newEmail': json['newEmail'],
        'password': json['password'],
    };
}

export function UpdateEmailRequestToJSON(value?: UpdateEmailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'newEmail': value.newEmail,
        'password': value.password,
    };
}

