/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Request sent to server to update account email address
 * @export
 * @interface UpdateAccountEmailRequest
 */
export interface UpdateAccountEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountEmailRequest
     */
    newEmail: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountEmailRequest
     */
    password: string;
}

/**
 * Check if a given object implements the UpdateAccountEmailRequest interface.
 */
export function instanceOfUpdateAccountEmailRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "newEmail" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UpdateAccountEmailRequestFromJSON(json: any): UpdateAccountEmailRequest {
    return UpdateAccountEmailRequestFromJSONTyped(json, false);
}

export function UpdateAccountEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountEmailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newEmail': json['newEmail'],
        'password': json['password'],
    };
}

export function UpdateAccountEmailRequestToJSON(value?: UpdateAccountEmailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'newEmail': value.newEmail,
        'password': value.password,
    };
}

