/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum UserPresence {
    offline = 'offline',
    doNotDisturb = 'doNotDisturb',
    inactive = 'inactive',
    online = 'online'
}


export function UserPresenceFromJSON(json: any): UserPresence {
    return UserPresenceFromJSONTyped(json, false);
}

export function UserPresenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPresence {
    return json as UserPresence;
}

export function UserPresenceToJSON(value?: UserPresence | null): any {
    return value as any;
}

