/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum UserRelationType {
    none = 'none',
    friend = 'friend',
    blocked = 'blocked'
}


export function UserRelationTypeFromJSON(json: any): UserRelationType {
    return UserRelationTypeFromJSONTyped(json, false);
}

export function UserRelationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRelationType {
    return json as UserRelationType;
}

export function UserRelationTypeToJSON(value?: UserRelationType | null): any {
    return value as any;
}

