/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserOnlineStatus } from './UserOnlineStatus';
import {
    UserOnlineStatusFromJSON,
    UserOnlineStatusFromJSONTyped,
    UserOnlineStatusToJSON,
} from './UserOnlineStatus';

/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    profilePictureId?: string;
    /**
     * 
     * @type {UserOnlineStatus}
     * @memberof UserDto
     */
    status?: UserOnlineStatus;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    statusText?: string;
    /**
     * Date this user was created at
     * @type {Date}
     * @memberof UserDto
     */
    createdAt?: Date;
    /**
     * Last time this user was online
     * @type {Date}
     * @memberof UserDto
     */
    lastOnline?: Date;
}

/**
 * Check if a given object implements the UserDto interface.
 */
export function instanceOfUserDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserDtoFromJSON(json: any): UserDto {
    return UserDtoFromJSONTyped(json, false);
}

export function UserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'profilePictureId': !exists(json, 'profile_picture_id') ? undefined : json['profile_picture_id'],
        'status': !exists(json, 'status') ? undefined : UserOnlineStatusFromJSON(json['status']),
        'statusText': !exists(json, 'status_text') ? undefined : json['status_text'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'lastOnline': !exists(json, 'last_online') ? undefined : (new Date(json['last_online'])),
    };
}

export function UserDtoToJSON(value?: UserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
        'profile_picture_id': value.profilePictureId,
        'status': UserOnlineStatusToJSON(value.status),
        'status_text': value.statusText,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'last_online': value.lastOnline === undefined ? undefined : (value.lastOnline.toISOString()),
    };
}

