/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum UserFriendStatus {
    none = 'none',
    friendRequestOutgoing = 'friendRequestOutgoing',
    friendRequestIncoming = 'friendRequestIncoming',
    friends = 'friends',
    blocked = 'blocked'
}


export function UserFriendStatusFromJSON(json: any): UserFriendStatus {
    return UserFriendStatusFromJSONTyped(json, false);
}

export function UserFriendStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFriendStatus {
    return json as UserFriendStatus;
}

export function UserFriendStatusToJSON(value?: UserFriendStatus | null): any {
    return value as any;
}

