/* tslint:disable */
/* eslint-disable */
/**
 * ZapMe
 * Open source application to control things
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebRtcConfig
 */
export interface WebRtcConfig {
    /**
     * 
     * @type {boolean}
     * @memberof WebRtcConfig
     */
    enabled: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebRtcConfig
     */
    approvedStunServers: Array<string>;
}

/**
 * Check if a given object implements the WebRtcConfig interface.
 */
export function instanceOfWebRtcConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enabled" in value;
    isInstance = isInstance && "approvedStunServers" in value;

    return isInstance;
}

export function WebRtcConfigFromJSON(json: any): WebRtcConfig {
    return WebRtcConfigFromJSONTyped(json, false);
}

export function WebRtcConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebRtcConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'approvedStunServers': json['approvedStunServers'],
    };
}

export function WebRtcConfigToJSON(value?: WebRtcConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'approvedStunServers': value.approvedStunServers,
    };
}

